name: Deploy Airflow DAGs

on:
  push:
    branches: [ main ]
    paths:
      - 'airflow/dags/**'

env:
  AIRFLOW_DAGS_FOLDER: /home/airflow/dags

jobs:
  deploy:
    name: Deploy DAGs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Copy DAGs to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "dags/*"
          target: "${{ env.AIRFLOW_DAGS_FOLDER }}"
          strip_components: 1

      - name: Verify deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            ls -l ${{ env.AIRFLOW_DAGS_FOLDER }}
            airflow dags list